package gr.ds.unipi.shapes;

public enum Position {
    BOTTOM, TOP, RIGHT, LEFT, BOTTOMRIGHT, BOTTOMLEFT, TOPRIGHT, TOPLEFT,
    BOTTOMRIGHTQUARTER, BOTTOMLEFTQUARTER, TOPRIGHTQUARTER, TOPLEFTQUARTER, PLAIN
}
